name: ExtDN M2 Mess Detector
on:
  push:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - README.md
  pull_request:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - README.md
jobs:
  phpmd:
    name: M2 Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-mess-detector@master